# -*- coding: utf-8 -*-
"""CSC625Algorithm_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18a_zi7XrRDl4Z-6yZ-ASVXldPbh6Mihp
"""

"""
Anonymous Algorithm 1
Backtracking Powerset

Victor Morgan and Ahmed Abdallah
04/24/2026

This code recreates algorithm 1, which we have confirmed to produce the powerset
of a given array.

A is our input array, N is the size of that array, and B is an empty array which
this algorithm uses to store the variables of our array in cases where the
integer from array in is included or not included. This algorithm only works in
cases where A does not contain 0. i is our iterative component which goes into
each compute call where A[i] is either included or not included in that iteration
of B. Dump B then prints only the values from A that are not 0. An example of B
is [0, 9, 0, 2, 0] displayed as the power set [9, 2]. K was used to store each
power set so that they could be viewed as such.

Count simply keeps count of how many powersets were produced. Counting and printing
were used to determine algorithm function, and commented out for time assessment.

"""
import time

#count = 1

def Algorithm1(A, N):
  B = [0] * N
  Compute(A,B,0, N)
  return
def Compute(A, B, i, N):
  if i > N-1:
    Dump(B)
    return
  B[i] = 0
  Compute(A,B,i+1, N)
  B[i] = A[i]
  Compute(A,B,i+1, N)
  B[i] = 0
  return

def Dump(B):
  #global count
  k = []
  for j in B:
    if j != 0:
      k.append(j)
  #print(count, ": ", k)
  #count += 1
  return

if __name__ == "__main__":
  A = [7, 9, 18, 2, 6]
  C = [7, 9, 18, 2, 6, 3, 4, 5, 8, 10]
  D = [7, 9, 18, 2, 6, 3, 4, 5, 8, 10, 12, 11, 15, 13, 14]
  E = [7, 9, 18, 2, 6, 3, 4, 5, 8, 10, 12, 11, 15, 13, 14, 17, 16, 19, 20, 1]

  #"Decoy" run to remove variable initialization from time equation
  start = time.time()
  Algorithm1(A, len(A))
  end = time.time()
  ATime = end - start

  start = time.time()
  Algorithm1(A, len(A))
  end = time.time()
  ATime = end - start

  start = time.time()
  Algorithm1(C, len(C))
  end = time.time()
  CTime = end - start

  start = time.time()
  Algorithm1(D, len(D))
  end = time.time()
  DTime = end - start

  start = time.time()
  Algorithm1(E, len(E))
  end = time.time()
  ETime = end - start

  print("Execution time on 5 elements   = ", (ATime*100000))
  print("Execution time on 10 elements  = ", (CTime*100000))
  print("Execution time on 15 elements  = ", (DTime*100000))
  print("Execution time on 20 elements  = ", (ETime*100000))