# -*- coding: utf-8 -*-
"""Algorithm4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ouj4UCpdzRUtHnPOqXLphhBNA9ZJw5gj
"""

"""
Anonymous Algorithm 4
Randomized Quickselect

Victor Morgan and Ahmed Abdallah
04/24/2026

Thisw program implements the Randomized Quickselect algorithm to find the median
element of our given array, A of length N. The algorithms repeatedly selects a random
pivot element and partitions the array around that pivot, moving smaller elements
to the left and larger to the right. THis places the pivot in it's sorted position
and the algorithm then determines if it is in the center or not. k is used to
determine if the algorithm is in the correct position, p is the lower bound of the
array, and r the upper bound. i serves as the desired position (median) of the
array.

"""

import time
import random

def Algorithm4(A, N):
  i = N//2
  val = Compute(A, 0, N-1, i)
  Dump(val)

def Compute(A, p, r, i):
  if p == r:
    return A[p]
  n = random.randint(p, r)
  A[n], A[r] = A[r], A[n]
  n = A[r]
  q = p-1
  for j in range(p, r):
    if A[j] < n:
      q += 1
      A[q], A[j] = A[j], A[q]
  q += 1
  A[q], A[r] = A[r], A[q]
  k = q-p+1
  if i == k:
    return A[q]
  elif i < k:
    return Compute(A, p, q-1, i)
  else:
    return Compute(A, q+1, r, i-k)

def Dump(val):
  print(val)



if __name__ == "__main__":
  A = [7, 9, 18, 2, 6]
  C = [7, 9, 18, 2, 6, 3, 4, 5, 8, 10]
  D = [7, 9, 18, 2, 6, 3, 4, 5, 8, 10, 12, 11, 15, 13, 14]
  E = [7, 9, 18, 2, 6, 3, 4, 5, 8, 10, 12, 11, 15, 13, 14, 17, 16, 19, 20, 1]

  #"Decoy" run to remove variable initialization from time equation
  start = time.time()
  Algorithm4(A, len(A))
  end = time.time()
  ATime = end - start

  start = time.time()
  Algorithm4(A, len(A))
  end = time.time()
  ATime = end - start

  start = time.time()
  Algorithm4(C, len(C))
  end = time.time()
  CTime = end - start

  start = time.time()
  Algorithm4(D, len(D))
  end = time.time()
  DTime = end - start

  start = time.time()
  Algorithm4(E, len(E))
  end = time.time()
  ETime = end - start

  print("Execution time on 5 elements   = ", (ATime*100000))
  print("Execution time on 10 elements  = ", (CTime*100000))
  print("Execution time on 15 elements  = ", (DTime*100000))
  print("Execution time on 20 elements  = ", (ETime*100000))